### PR TITLE
Update Bazel dependencies

### PR DESCRIPTION
**Pull request by jpsim**
Updates the following, mostly in order to support rules_swift 2.x:

* Bazel version defined in `.bazelversion` to the latest stable release (7.2.1)
* Add `apple_support` (required for Bazel 7.x)
* Update `platforms`: 0.0.8 -> 0.0.9
* Update `rules_apple`: 3.1.1 -> 3.6.0
* Update `rules_swift`: 1.13.0 -> 2.1.1

Also update tests to pass CI since it looks like GitHub's macOS runner image environments may have changed recently.

### CODE REVIEW

**Comment by jpsim** [comment]
FYI @Keith cc'ing you because I'm not aware of other maintainers for this project.

**Review by keith — APPROVED** [review]

**Comment by keith** [comment]
nice, thanks

**Comment by jpsim** [comment]
Thanks! Any chance you could tag a release + BCR update with these changes? 🙏

**Comment by keith** [comment]
done https://github.com/bazelbuild/bazel-central-registry/pull/2422

**Comment by keith** [comment]
also added you as a maintainer

**Pull request merged**
